spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
spring.servlet.multipart.max-file-size=20MB
# ???????? ?????? ????? ???????
spring.servlet.multipart.max-request-size=20MB
spring.security.oauth2.client.registration.yandex.client-id=client-id
spring.security.oauth2.client.registration.yandex.client-secret=client-secret
spring.security.oauth2.client.registration.yandex.client-name=Yandex
spring.security.oauth2.client.registration.yandex.provider=yandex
spring.security.oauth2.client.registration.yandex.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.yandex.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.yandex.scope=login:email,login:info

spring.security.oauth2.client.provider.yandex.authorization-uri=https://oauth.yandex.ru/authorize
spring.security.oauth2.client.provider.yandex.token-uri=https://oauth.yandex.ru/token
spring.security.oauth2.client.provider.yandex.user-info-uri=https://login.yandex.ru/info?format=json
spring.security.oauth2.client.provider.yandex.user-name-attribute=id
app.jwt.secret=your-very-long-random-secret-string-at-least-32-chars
app.jwt.expirationSeconds=86400
